### ISSUE TITLE
Postponed features from alpha 5.4

### ISSUE THREAD

**Issue by Ippo343** [Ippo343/DangIt#102]
Hi @602p ,

I took the liberty to postpone the remaining 0.5.4 features to 0.7 as I'm pretty confident I'm almost ready with 0.6.
The transition to the stock XP system looks pretty painless: it just needs some testing but I think it can be released in a couple of days, within the weekend tops.

Cheers!

**Comment by 602p** [comment]
Alright, sounds good!
