### ISSUE TITLE
ModuleGimbalReliability breaks if saved while failed

### ISSUE THREAD

**Issue by 602p** [Ippo343/DangIt#107]
Upon reloading, attempting to acquire a handle to ModuleGimbal fails and you get a ton of NullReferenceExceptions.

**Comment by Ippo343** [comment]
Well, that was the reason why I originally decided not to remove modules dynamically.
One year later, I fell for that. Sorry :/

**Comment by 602p** [comment]
No problem. I think I've got a fix for it. I'll push it to the 1.0 branch when I get it working.

**Comment by 602p** [comment]
Fixed.
