### ISSUE TITLE
life support / air circulation breaking / pumps breaking

### ISSUE THREAD

**Issue by anxcon** [Ippo343/DangIt#110]
i don't know if this is possible for dangit, but

so life support mods have oxygen, you need oxygen to breathe
say i have a ship that is just 2 pods, if a valve ever breaks etc in pod`1, air wouldn't come out of said tanks, pod 2 still works, i think most life support mods would have the kerbal using pod2 air though - or does it take into account the "flow" ability of the resource which would be nice?;p

either case what i want is a way for "flow" to break between parts, say i have 2 tanks, after a point pump breaks on tank 1, i cant transfer between - or should that only allow cant pump "out"? so 2 could still pump into 1, perhaps the module lets you pick :)

**Comment by 602p** [comment]
I think TACLS at least calculates on a vessel-wide basis. Disabling fuel crossfeed is definatley possible though.

You could use the transfer GUI to get around it, that would be a fun Apollo-13-like mechanic!

I've got end of year school stuff, but I can look at it in like 2 weeks :-)

**Comment by anxcon** [comment]
is there a way to disable transfer GUI in the same bit?
like you can't transfer SRB solidfuel :) no auto flow, nada

**Comment by CovertJaguar** [comment]
You could have USI LS recycler modules fail probably.

**Comment by Ippo343** [comment]
I think this is a little bit too detailed and also very different to model.
