### ISSUE TITLE
Tank leaking module tweak

### ISSUE THREAD

**Issue by anxcon** [Ippo343/DangIt#112]
this might be more for entropy, don't know

if i stack up 2 tanks of LF+O, both with moduletankreliability, 1st tank fails (gets a "leak") and everything is leaked out, but 2nd tank is fine - dependant on the resource used (its flow type or such) the pump in the 2nd tank should be pumping it into the 1st (not really, just faked) so should leak as well but as a very slow rate (pumps regulate pressure, so the exponential loss by volume mechanic wouldnt apply here)

and the 2nd tank should instantly be uneffected when the resource is shut off in right click menu of 2nd tank (or should the lock go onto 1st tank? 1 click to shut off pumping "in" is the thought, less tanks to disable)

**Comment by 602p** [comment]
Hm. Interesting thought. I think that tanks in KSP are probably individual pressure vessels, and as such can leak independently. When I figure out how to add tank reliability to procedural parts that will be a much bigger issue, I think.

I'll leave it here and see what Ippo thinks. :)

**Comment by anxcon** [comment]
i got around PP+Dangit issue by using MFT,  works perfect, sure a direct fix isnt bad, just figured i'd list the bandaid (and i prefer MFT anyways) incase people see it :)

**Comment by Ippo343** [comment]
Well, as it works right now we try to use the `RequestResource` method which will fetch it from anywhere using the fuel flow rules.
If we can't use the clean method (i.e, the tank's valves have been closed) then we subtract it directly.

So tanks are connected until you shut the valves closed, which means that having multiple tanks (redundancy) makes you safer.
