### ISSUE TITLE
incomplete script? bug? alternator

### ISSUE THREAD

**Issue by anxcon** [Ippo343/DangIt#114]
current script for ModuleAlternatorReliability
@PART[*]:HAS[@MODULE[ModuleEngines],@MODULE[ModuleAlternator],!MODULE[NoFailureModules]]:FOR[DangIt]

this applies to engines with ModuleEngines but not ModuleEnginesFX (the old nasa stuff)
any reasons to this? would this work on engines with ModuleEnginesFX?
does this module even care about engines or simply that ModuleAlternator exists?

nasa stuff should break too :)

**Comment by anxcon** [comment]
accually this questions should apply to ModuleGimbalReliability as well, same issue

**Comment by Ippo343** [comment]
You are right, it should be `ModuleEngine*`.
Will fix at the next chance :)
