### ISSUE TITLE
Discrete slider for spares

### ISSUE THREAD

**Issue by Ippo343** [Ippo343/DangIt#116]
Using KSP API Extensions, it should be possible to implement a slider with integer values (as having half spare part makes no sense.

**Comment by 602p** [comment]
This and #115 are both pretty simple. When I'm finally free from high school for the summer this weekend I'll set them up.

**Comment by 602p** [comment]
Ended up being more complicated then I would have liked. UI_FloatEdit can't be applied to Resources, and a transition layer was way more complicated than this simple fix.
