### ISSUE TITLE
kRPC Compatibility?

### ISSUE THREAD

**Issue by pbeart** [Ippo343/DangIt#124]
kRPC compatibility would be very useful: it would allow external UIs to be built showing part failure modes etc, and allow those running mission control scenarios a more realistic way to interact with the mod. I have no experience at all with C, but hopefully it wouldn't be too difficult to implement compatibility using the [kRPC Service API](https://krpc.github.io/krpc/extending.html), and would be very much appreciated.

**Comment by Ippo343** [comment]
Hi @pbeart ! I have abandoned this project a while ago. If I'm not mistaken it has been adopted by @linuxgurugamer , you should reopen your issue [here](https://github.com/linuxgurugamer/DangIt).
Cheers!
