### ISSUE TITLE
MissionControllerExtended breaks taking spareparts

### ISSUE THREAD

**Issue by 602p** [Ippo343/DangIt#83]
It would appear to be caused by...
http://forum.kerbalspaceprogram.com/threads/93627-0-25-Kerbal-EVA-Resource-Transfer-v1-1-2-08-10-2014
reported here: http://forum.kerbalspaceprogram.com/threads/81794-0-25-Alpha-4-4-Dang-It%21-Now-up-for-adoption-%28?p=1583780&viewfull=1#post1583780

Perhaps we should move to use CIT KERT outright?

**Comment by D33pfield** [comment]
I too am experiencing this. Possible conflicting mods are:
-MKS/OKS
-Mission Controller 2
-KERT

**Comment by 602p** [comment]
As of pulling @TrypChangeling 's changes this is fixed.
